version: "3.9"
name: UniCourse Backend

services:
  db:
    image: postgres:14-alpine
    container_name: unicourse-backend-db
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      target: backend
    image: unicourse-backend:latest
    container_name: unicourse-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db

  adminer:
    image: adminer:4-standalone
    container_name: unicourse-backend-adminer
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - db

  dev:
    build:
      context: .
      target: dev
    image: unicourse-backend-dev:latest
    container_name: unicourse-backend-dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
      - adminer
    volumes:
      - .:/app
    stop_signal: SIGKILL

volumes:
  postgres-data: {}
