version: "3.9"
name: unicourse-workspace

services:
  db:
    image: postgres:15-alpine
    container_name: unicourse-backend-db
    restart: unless-stopped
    env_file:
      - ../.env
    expose:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer:4-standalone
    container_name: unicourse-backend-adminer
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - db

  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspace
    depends_on:
      - db
      - adminer
    command: sleep infinity

volumes:
  postgres-data: {}
