name: Deploy

on:
  workflow_run:
    workflows: ["Publish Docker Image"]
    types: ["completed"]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # If new docker image is published successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd unicourse-deploy
            ./update.sh
